name: Build and Push Docker Image

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: markac007/discord-ai-bot

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU (multi-arch)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == false) }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract image metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            # On PRs from same repo: tag with PR number and short SHA
            type=raw,value=pr-${{ github.event.number }},enable=${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == false }}
            type=sha,prefix=pr-${{ github.event.number }}-sha-,enable=${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == false }}

            # On pushes to main (post-merge): tag as latest and with SHA
            type=raw,value=latest,enable=${{ github.event_name == 'push' && startsWith(github.ref, 'refs/heads/main') }}
            type=sha,prefix=sha-,enable=${{ github.event_name == 'push' && startsWith(github.ref, 'refs/heads/main') }}

            # On version tags like v1.2.3: use semver tags
            type=semver,pattern={{version}},enable=${{ startsWith(github.ref, 'refs/tags/v') }}
            type=semver,pattern={{major}}.{{minor}},enable=${{ startsWith(github.ref, 'refs/tags/v') }}

      - name: Show computed tags
        run: |
          echo "Computed tags: ${{ steps.meta.outputs.tags }}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == false) }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
